// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBGd-MV9M7geArWFYEFCOsFNwruDZfSV4',
    appId: '1:283398482642:web:e29ee569d9a9c5766b5b0b',
    messagingSenderId: '283398482642',
    projectId: 'immunowarriors-groupe05',
    authDomain: 'immunowarriors-groupe05.firebaseapp.com',
    storageBucket: 'immunowarriors-groupe05.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1vkWBzqlm_2IfQNvQi3jYBvZk8ky-6tE',
    appId: '1:283398482642:android:f328e9fb321c904b6b5b0b',
    messagingSenderId: '283398482642',
    projectId: 'immunowarriors-groupe05',
    storageBucket: 'immunowarriors-groupe05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcrdddQ0oHNTft9-JwoFSWvR7_zR1C3HM',
    appId: '1:283398482642:ios:249f143602ccb0096b5b0b',
    messagingSenderId: '283398482642',
    projectId: 'immunowarriors-groupe05',
    storageBucket: 'immunowarriors-groupe05.firebasestorage.app',
    iosBundleId: 'com.example.immunoWarriors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcrdddQ0oHNTft9-JwoFSWvR7_zR1C3HM',
    appId: '1:283398482642:ios:249f143602ccb0096b5b0b',
    messagingSenderId: '283398482642',
    projectId: 'immunowarriors-groupe05',
    storageBucket: 'immunowarriors-groupe05.firebasestorage.app',
    iosBundleId: 'com.example.immunoWarriors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBGd-MV9M7geArWFYEFCOsFNwruDZfSV4',
    appId: '1:283398482642:web:e3c62ec1cb222c936b5b0b',
    messagingSenderId: '283398482642',
    projectId: 'immunowarriors-groupe05',
    authDomain: 'immunowarriors-groupe05.firebaseapp.com',
    storageBucket: 'immunowarriors-groupe05.firebasestorage.app',
  );
}
